[package]
name = "aegis-vault"
version = "0.1.0"
description = "AEGIS Vault Program (skeleton)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "aegis_vault"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
